# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tim Johnston's Personal Page
email: tedwardj11@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Thanks for coming by. This page serves as my personal blog and portfolio, with regular blog posts and links to my social and professional media profiles.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: TimJohnston_11
github_username:  timothy-johnston

# Build settings
markdown: kramdown
