# Site settings
title: "Tim Johnston"
email: tedwardj11@gmail.com
description: "My personal page."
baseurl: ""
url: "https://timothy-johnston.github.io/"
title_description: "| Software developer |<br>| Logic, creativity, structure |<br>| See my Twitter, GitHub, and LinkedIn for more |"
title_image: "/assets/weddingCrop2.png"
google_analytics: "UA-20365477-4"
disqus_account: cartenoire
github_repository: https://github.com/jacobtomlinson/carte-noire
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: TimJohnston_11
github_username:  timothy-johnston
instagram_username:
reddit_username:
linkedin_link: https://www.linkedin.com/in/timothyejohnston/
google_plus_link:
stackoverflow_link:
xing_link:
facebook_link:

# Footer
footer_left: "Theme is Carte-Noir, <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]

