# Site settings
title: "Tim Johnston"
email: tedwardj11@gmail.com
description: "My personal page."
baseurl: ""
url: "https://timothy-johnston.github.io/"
title_description: "Logic, creativity, structure<br>Software development student<br><a href=\"/assets/resumeLong.pdf\">Resume</a> | <a href=\"https://timothy-johnston.github.io/jekyll/update/2018/06/15/my-portfolio/\">Projects</a> | <a href=\"https://github.com/timothy-johnston\">GitHub</a> | <a href=\"https://www.linkedin.com/in/timothyejohnston/\">LinkedIn</a> | <a href=\"https://twitter.com/TimJohnston_11\">Twitter</a>"
title_image: "/assets/weddingCrop2.png"
google_analytics: "UA-20365477-4"
disqus_account: cartenoire
github_repository: https://github.com/jacobtomlinson/carte-noire
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
#twitter_username: TimJohnston_11
#github_username:  timothy-johnston
instagram_username:
reddit_username:
#linkedin_link: https://www.linkedin.com/in/timothyejohnston/
google_plus_link:
stackoverflow_link:
xing_link:
facebook_link:

# Footer
footer_left: "Theme is Carte-Noir, <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]

